name: Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  health_check_test:
    needs: build
    uses: ./.github/workflows/health_check_test.yml
