name: Build e Executar Testes

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construir o projeto
        run: mvn clean package -DskipTests

      - name: Salvar Build como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: projeto-build
          path: target/

  test:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Baixar Build
        uses: actions/download-artifact@v4
        with:
          name: projeto-build
          path: target/

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Executar Testes
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testes/healthCheck.xml
