name: Build Projeto

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construir o projeto
        run: mvn clean package

      - name: Salvar Build como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: projeto-build
          path: target/