name: Java CI para executar testes e salvar report no GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build do projeto
        run: mvn clean install -DskipTests

      - name: Salvar workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  test-contrato:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Baixar workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - name: Executar testes de Contrato
        run: mvn test -Dgroups=Contrato
        continue-on-error: true

      - name: Coletar resultados do Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-contrato
          path: target/allure-results

  test-funcional:
    runs-on: ubuntu-latest
    needs: test-contrato

    steps:
      - name: Baixar workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - name: Executar testes Funcionais
        run: mvn test -Dgroups=Funcional
        continue-on-error: true

      - name: Coletar resultados do Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-funcional
          path: target/allure-results

  generate-allure-report:
    runs-on: ubuntu-latest
    needs: test-funcional
    if: always()
    permissions:
      contents: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Baixar resultados do Allure
        uses: actions/download-artifact@v4
        with:
          path: allure-results

      - name: Gerar e publicar Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: allure-history