name: Pipeline Github Actions

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

  health-check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Health Check
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testes/healthCheck.xml

  contrato:
    runs-on: ubuntu-latest
    needs: health-check

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Contrato
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testes/contrato.xml

  funcional:
    runs-on: ubuntu-latest
    needs: contrato

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Funcional
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testes/funcional.xml

  allure:
    runs-on: ubuntu-latest
    needs: funcional
    if: always()
    permissions:
      contents: write
    steps:
    - name: Get allure history
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action
      uses: simple-elf/allure-report-action@master
      with:
        allure_results: target/allure-results
        allure_history: allure-history/allure-history
        keep_reports: 5

    - name: Deploy report to Github Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: allure-history/allure-history

  code-ql-analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: read

    strategy:
      fail-fast: false
      matrix:
        language: ['java']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Init CodeQL
      uses: github/codeql-action/init@v2
      with:
        language: ${{matrix.language}}
        
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
      
    - name: CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
  

