allure:
  runs-on: ubuntu-latest
  needs: funcional
  if: always()
  permissions:
    contents: write
  steps:
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # Aqui usa o token pessoal
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
