name: Pipeline Github Actions

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build do projeto
        run: mvn clean install -DskipTests

  health-check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar testes de Health Check
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testes/healthCheck.xml

      - name: Coletar resultados do Allure
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-health-check
          path: target/allure-results

  contrato:
    runs-on: ubuntu-latest
    needs: health-check

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar testes de Contrato
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testes/contrato.xml

      - name: Coletar resultados do Allure
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-contrato
          path: target/allure-results

  funcional:
    runs-on: ubuntu-latest
    needs: contrato

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar testes Funcionais
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testes/funcional.xml

      - name: Coletar resultados do Allure
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-funcional
          path: target/allure-results

  allure:
    runs-on: ubuntu-latest
    needs: [health-check, contrato, funcional]
    if: always()
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Baixar resultados do Allure
        uses: actions/download-artifact@v3
        with:
          path: allure-results

      - name: Gerar Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history