name: Pipeline Github Actions

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

  health-check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Health Check
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testes/healthCheck.xml

  contrato:
    runs-on: ubuntu-latest
    needs: health-check

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Contrato
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testes/contrato.xml

  funcional:
    runs-on: ubuntu-latest
    needs: contrato

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Funcional
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testes/funcional.xml

  allure:
    runs-on: ubuntu-latest
    needs: funcional
    if: always()
    permissions:
      contents: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: main
          path: main

      - name: Gerar relatório do Allure
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: /allure-results/
          gh_pages: main
          allure_report: allure-report
          allure_history: allure-history

      - name: Verificar arquivos antes do deploy
        run: ls -R allure-history

      - name: Deploy do relatório para GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: allure-history

